version: '3'
services:

  postgresql:
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:16.0-alpine3.18

  php:
    container_name: php
    image: php:fpm
    volumes:
      - './src:/var/www/html'

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

