version: '3'
services:

  postgresql:
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:16.0-alpine3.18
    restart: always

  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./:/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=test"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/app
    depends_on:
      - php-fpm
    restart: always

